import Footer from '@/app/Footer'
import Header from '@/app/Header'
import { Providers } from '@/app/providers'
import { Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers attribute="class" defaultTheme="system" enableSystem>
          <Theme
            accentColor="indigo"
            grayColor="slate"
            radius="small"
            scaling="100%"
            panelBackground="translucent"
          >
            <div className="flex w-full flex-col items-center">
              <div className="flex min-h-screen w-full flex-col items-center justify-start">
                <Header />
                {children}
              </div>
              <Footer />
            </div>
          </Theme>
        </Providers>
      </body>
    </html>
  )
}
