import { Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Theme
          accentColor="indigo"
          grayColor="slate"
          radius="small"
          scaling="100%"
          panelBackground="translucent"
        >
          {children}
        </Theme>
      </body>
    </html>
  )
}
