export const CLUB_NAMES = [
  'Africa/South Africa',
  'Asia',
  'Atlantic',
  'Australia/NZ',
  'Benelux',
  'Brazil',
  'California Club',
  'Canada',
  'Carolina',
  'Celtic',
  'Central-Eastern Europe',
  'Connecticut',
  'DE-AT-CH',
  'Finland',
  'Florida',
  'France',
  'Georgia',
  'Great Plains',
  'Hispanoamérica',
  'Iberia',
  'Illinois',
  'Indiana',
  'International Club',
  'Italy',
  'Japan',
  'Massachusetts',
  'Mexico',
  'Michigan',
  'Mid-South',
  'Midwest',
  'New England',
  'New Jersey',
  'New York',
  'Northwest',
  'Ohio',
  'Pennsylvania',
  'Scandinavia',
  'Texas',
  'UK and I',
  'Virginias',
  'West',
  'Western Canada',
]

export const COUNTRIES = [
  {
    country_name: 'Afghanistan',
    country_code: 'AF',
    flag: '🇦🇫',
  },
  {
    country_name: 'Aland Islands',
    country_code: 'AX',
    flag: '🇦🇽',
  },
  {
    country_name: 'Albania',
    country_code: 'AL',
    flag: '🇦🇱',
  },
  {
    country_name: 'Algeria',
    country_code: 'DZ',
    flag: '🇩🇿',
  },
  {
    country_name: 'American Samoa (US)',
    country_code: 'AS',
    flag: '🇦🇸',
  },
  {
    country_name: 'Andorra',
    country_code: 'AD',
    flag: '🇦🇩',
  },
  {
    country_name: 'Angola',
    country_code: 'AO',
    flag: '🇦🇴',
  },
  {
    country_name: 'Anguilla (UK)',
    country_code: 'AI',
    flag: '🇦🇮',
  },
  {
    country_name: 'Antarctica',
    country_code: 'AQ',
    flag: '🇦🇶',
  },
  {
    country_name: 'Antigua and Barbuda',
    country_code: 'AG',
    flag: '🇦🇬',
  },
  {
    country_name: 'Argentina',
    country_code: 'AR',
    flag: '🇦🇷',
  },
  {
    country_name: 'Armenia',
    country_code: 'AM',
    flag: '🇦🇲',
  },
  {
    country_name: 'Aruba',
    country_code: 'AW',
    flag: '🇦🇼',
  },
  {
    country_name: 'Australia',
    country_code: 'AU',
    flag: '🇦🇺',
  },
  {
    country_name: 'Austria',
    country_code: 'AT',
    flag: '🇦🇹',
  },
  {
    country_name: 'Azerbaijan',
    country_code: 'AZ',
    flag: '🇦🇿',
  },
  {
    country_name: 'Bahamas',
    country_code: 'BS',
    flag: '🇧🇸',
  },
  {
    country_name: 'Bahrain',
    country_code: 'BH',
    flag: '🇧🇭',
  },
  {
    country_name: 'Bangladesh',
    country_code: 'BD',
    flag: '🇧🇩',
  },
  {
    country_name: 'Barbados',
    country_code: 'BB',
    flag: '🇧🇧',
  },
  {
    country_name: 'Belarus',
    country_code: 'BY',
    flag: '🇧🇾',
  },
  {
    country_name: 'Belgium',
    country_code: 'BE',
    flag: '🇧🇪',
  },
  {
    country_name: 'Belize',
    country_code: 'BZ',
    flag: '🇧🇿',
  },
  {
    country_name: 'Benin',
    country_code: 'BJ',
    flag: '🇧🇯',
  },
  {
    country_name: 'Bermuda (UK)',
    country_code: 'BM',
    flag: '🇧🇲',
  },
  {
    country_name: 'Bhutan',
    country_code: 'BT',
    flag: '🇧🇹',
  },
  {
    country_name: 'Bolivia',
    country_code: 'BO',
    flag: '🇧🇴',
  },
  {
    country_name: 'Bosnia and Herzegovina',
    country_code: 'BA',
    flag: '🇧🇦',
  },
  {
    country_name: 'Botswana',
    country_code: 'BW',
    flag: '🇧🇼',
  },
  {
    country_name: 'Brazil',
    country_code: 'BR',
    flag: '🇧🇷',
  },
  {
    country_name: 'British Virgin Islands (UK)',
    country_code: 'VG',
    flag: '🇻🇬',
  },
  {
    country_name: 'Brunei Darussalam',
    country_code: 'BN',
    flag: '🇧🇳',
  },
  {
    country_name: 'Bulgaria',
    country_code: 'BG',
    flag: '🇧🇬',
  },
  {
    country_name: 'Burkina Faso',
    country_code: 'BF',
    flag: '🇧🇫',
  },
  {
    country_name: 'Burundi',
    country_code: 'BI',
    flag: '🇧🇮',
  },
  {
    country_name: 'Cambodia',
    country_code: 'KH',
    flag: '🇰🇭',
  },
  {
    country_name: 'Cameroon',
    country_code: 'CM',
    flag: '🇨🇲',
  },
  {
    country_name: 'Canada',
    country_code: 'CA',
    flag: '🇨🇦',
  },
  {
    country_name: 'Cape Verde',
    country_code: 'CV',
    flag: '🇨🇻',
  },
  {
    country_name: 'Cayman Islands (UK)',
    country_code: 'KY',
    flag: '🇰🇾',
  },
  {
    country_name: 'Central African Republic',
    country_code: 'CF',
    flag: '🇨🇫',
  },
  {
    country_name: 'Chad',
    country_code: 'TD',
    flag: '🇹🇩',
  },
  {
    country_name: 'Chile',
    country_code: 'CL',
    flag: '🇨🇱',
  },
  {
    country_name: 'China',
    country_code: 'CN',
    flag: '🇨🇳',
  },
  {
    country_name: 'Christmas Island (AU)',
    country_code: 'CX',
    flag: '🇨🇽',
  },
  {
    country_name: 'Cocos (Keeling) Islands (AU)',
    country_code: 'CC',
    flag: '🇨🇨',
  },
  {
    country_name: 'Colombia',
    country_code: 'CO',
    flag: '🇨🇴',
  },
  {
    country_name: 'Congo, Democratic Republic of the',
    country_code: 'CD',
    flag: '🇨🇩',
  },
  {
    country_name: 'Congo, Republic of the',
    country_code: 'CG',
    flag: '🇨🇬',
  },
  {
    country_name: 'Costa Rica',
    country_code: 'CR',
    flag: '🇨🇷',
  },
  {
    country_name: 'Croatia',
    country_code: 'HR',
    flag: '🇭🇷',
  },
  {
    country_name: 'Cyprus',
    country_code: 'CY',
    flag: '🇨🇾',
  },
  {
    country_name: 'Czech Republic',
    country_code: 'CZ',
    flag: '🇨🇿',
  },
  {
    country_name: 'Denmark',
    country_code: 'DK',
    flag: '🇩🇰',
  },
  {
    country_name: 'Djibouti',
    country_code: 'DJ',
    flag: '🇩🇯',
  },
  {
    country_name: 'Dominica',
    country_code: 'DM',
    flag: '🇩🇲',
  },
  {
    country_name: 'Dominican Republic',
    country_code: 'DO',
    flag: '🇩🇴',
  },
  {
    country_name: 'Ecuador',
    country_code: 'EC',
    flag: '🇪🇨',
  },
  {
    country_name: 'Egypt',
    country_code: 'EG',
    flag: '🇪🇬',
  },
  {
    country_name: 'El Salvador',
    country_code: 'SV',
    flag: '🇸🇻',
  },
  {
    country_name: 'Equatorial Guinea',
    country_code: 'GQ',
    flag: '🇬🇶',
  },
  {
    country_name: 'Eritrea',
    country_code: 'ER',
    flag: '🇪🇷',
  },
  {
    country_name: 'Estonia',
    country_code: 'EE',
    flag: '🇪🇪',
  },
  {
    country_name: 'Ethiopia',
    country_code: 'ET',
    flag: '🇪🇹',
  },
  {
    country_name: 'Falkland Islands (UK)',
    country_code: 'FK',
    flag: '🇫🇰',
  },
  {
    country_name: 'Faroe Islands (DK)',
    country_code: 'FO',
    flag: '🇫🇴',
  },
  {
    country_name: 'Fiji',
    country_code: 'FJ',
    flag: '🇫🇯',
  },
  {
    country_name: 'Finland',
    country_code: 'FI',
    flag: '🇫🇮',
  },
  {
    country_name: 'France',
    country_code: 'FR',
    flag: '🇫🇷',
  },
  {
    country_name: 'French Guiana (FR)',
    country_code: 'GF',
    flag: '🇬🇫',
  },
  {
    country_name: 'French Polynesia (FR)',
    country_code: 'PF',
    flag: '🇵🇫',
  },
  {
    country_name: 'Gabon',
    country_code: 'GA',
    flag: '🇬🇦',
  },
  {
    country_name: 'Gambia',
    country_code: 'GM',
    flag: '🇬🇲',
  },
  {
    country_name: 'Georgia',
    country_code: 'GE',
    flag: '🇬🇪',
  },
  {
    country_name: 'Germany',
    country_code: 'DE',
    flag: '🇩🇪',
  },
  {
    country_name: 'Ghana',
    country_code: 'GH',
    flag: '🇬🇭',
  },
  {
    country_name: 'Gibraltar (UK)',
    country_code: 'GI',
    flag: '🇬🇮',
  },
  {
    country_name: 'Greece',
    country_code: 'GR',
    flag: '🇬🇷',
  },
  {
    country_name: 'Greenland (DK)',
    country_code: 'GL',
    flag: '🇬🇱',
  },
  {
    country_name: 'Grenada',
    country_code: 'GD',
    flag: '🇬🇩',
  },
  {
    country_name: 'Guadeloupe (FR)',
    country_code: 'GP',
    flag: '🇬🇵',
  },
  {
    country_name: 'Guam (US)',
    country_code: 'GU',
    flag: '🇬🇺',
  },
  {
    country_name: 'Guatemala',
    country_code: 'GT',
    flag: '🇬🇹',
  },
  {
    country_name: 'Guernsey',
    country_code: 'GG',
    flag: '🇬🇬',
  },
  {
    country_name: 'Guinea',
    country_code: 'GN',
    flag: '🇬🇳',
  },
  {
    country_name: 'Guinea-Bissau',
    country_code: 'GW',
    flag: '🇬🇼',
  },
  {
    country_name: 'Guyana',
    country_code: 'GY',
    flag: '🇬🇾',
  },
  {
    country_name: 'Haiti',
    country_code: 'HT',
    flag: '🇭🇹',
  },
  {
    country_name: 'Holy See (Vatican City)',
    country_code: 'VA',
    flag: '🇻🇦',
  },
  {
    country_name: 'Honduras',
    country_code: 'HN',
    flag: '🇭🇳',
  },
  {
    country_name: 'Hong Kong (CN)',
    country_code: 'HK',
    flag: '🇭🇰',
  },
  {
    country_name: 'Hungary',
    country_code: 'HU',
    flag: '🇭🇺',
  },
  {
    country_name: 'Iceland',
    country_code: 'IS',
    flag: '🇮🇸',
  },
  {
    country_name: 'India',
    country_code: 'IN',
    flag: '🇮🇳',
  },
  {
    country_name: 'Indonesia',
    country_code: 'ID',
    flag: '🇮🇩',
  },
  {
    country_name: 'Iraq',
    country_code: 'IQ',
    flag: '🇮🇶',
  },
  {
    country_name: 'Ireland',
    country_code: 'IE',
    flag: '🇮🇪',
  },
  {
    country_name: 'Isle of Man',
    country_code: 'IM',
    flag: '🇮🇲',
  },
  {
    country_name: 'Israel',
    country_code: 'IL',
    flag: '🇮🇱',
  },
  {
    country_name: 'Italy',
    country_code: 'IT',
    flag: '🇮🇹',
  },
  {
    country_name: 'Ivory Coast',
    country_code: 'CI',
    flag: '🇨🇮',
  },
  {
    country_name: 'Jamaica',
    country_code: 'JM',
    flag: '🇯🇲',
  },
  {
    country_name: 'Japan',
    country_code: 'JP',
    flag: '🇯🇵',
  },
  {
    country_name: 'Jersey, Island of',
    country_code: 'JE',
    flag: '🇯🇪',
  },
  {
    country_name: 'Jordan',
    country_code: 'JO',
    flag: '🇯🇴',
  },
  {
    country_name: 'Kazakhstan',
    country_code: 'KZ',
    flag: '🇰🇿',
  },
  {
    country_name: 'Kenya',
    country_code: 'KE',
    flag: '🇰🇪',
  },
  {
    country_name: 'Korea - Republic of (South)',
    country_code: 'KR',
    flag: '🇰🇷',
  },
  {
    country_name: 'Kuwait',
    country_code: 'KW',
    flag: '🇰🇼',
  },
  {
    country_name: 'Kyrgyzstan',
    country_code: 'KG',
    flag: '🇰🇬',
  },
  {
    country_name: 'Laos',
    country_code: 'LA',
    flag: '🇱🇦',
  },
  {
    country_name: 'Latvia',
    country_code: 'LV',
    flag: '🇱🇻',
  },
  {
    country_name: 'Lebanon',
    country_code: 'LB',
    flag: '🇱🇧',
  },
  {
    country_name: 'Lesotho',
    country_code: 'LS',
    flag: '🇱🇸',
  },
  {
    country_name: 'Libya',
    country_code: 'LY',
    flag: '🇱🇾',
  },
  {
    country_name: 'Liechtenstein',
    country_code: 'LI',
    flag: '🇱🇮',
  },
  {
    country_name: 'Lithuania',
    country_code: 'LT',
    flag: '🇱🇹',
  },
  {
    country_name: 'Luxembourg',
    country_code: 'LU',
    flag: '🇱🇺',
  },
  {
    country_name: 'Macau (CN)',
    country_code: 'MO',
    flag: '🇲🇴',
  },
  {
    country_name: 'Macedonia',
    country_code: 'MK',
    flag: '🇲🇰',
  },
  {
    country_name: 'Madagascar',
    country_code: 'MG',
    flag: '🇲🇬',
  },
  {
    country_name: 'Malawi',
    country_code: 'MW',
    flag: '🇲🇼',
  },
  {
    country_name: 'Malaysia',
    country_code: 'MY',
    flag: '🇲🇾',
  },
  {
    country_name: 'Maldives',
    country_code: 'MV',
    flag: '🇲🇻',
  },
  {
    country_name: 'Mali',
    country_code: 'ML',
    flag: '🇲🇱',
  },
  {
    country_name: 'Malta',
    country_code: 'MT',
    flag: '🇲🇹',
  },
  {
    country_name: 'Marshall Islands',
    country_code: 'MH',
    flag: '🇲🇭',
  },
  {
    country_name: 'Martinique (FR)',
    country_code: 'MQ',
    flag: '🇲🇶',
  },
  {
    country_name: 'Mauritania',
    country_code: 'MR',
    flag: '🇲🇷',
  },
  {
    country_name: 'Mauritius',
    country_code: 'MU',
    flag: '🇲🇺',
  },
  {
    country_name: 'Mayotte (FR)',
    country_code: 'YT',
    flag: '🇾🇹',
  },
  {
    country_name: 'Mexico',
    country_code: 'MX',
    flag: '🇲🇽',
  },
  {
    country_name: 'Micronesia, Federated States of',
    country_code: 'FM',
    flag: '🇫🇲',
  },
  {
    country_name: 'Moldova Republic of',
    country_code: 'MD',
    flag: '🇲🇩',
  },
  {
    country_name: 'Monaco',
    country_code: 'MC',
    flag: '🇲🇨',
  },
  {
    country_name: 'Mongolia',
    country_code: 'MN',
    flag: '🇲🇳',
  },
  {
    country_name: 'Montenegro',
    country_code: 'ME',
    flag: '🇲🇪',
  },
  {
    country_name: 'Montserrat (UK)',
    country_code: 'MS',
    flag: '🇲🇸',
  },
  {
    country_name: 'Morocco',
    country_code: 'MA',
    flag: '🇲🇦',
  },
  {
    country_name: 'Mozambique',
    country_code: 'MZ',
    flag: '🇲🇿',
  },
  {
    country_name: 'Myanmar',
    country_code: 'MM',
    flag: '🇲🇲',
  },
  {
    country_name: 'Namibia',
    country_code: 'NA',
    flag: '🇳🇦',
  },
  {
    country_name: 'Nepal',
    country_code: 'NP',
    flag: '🇳🇵',
  },
  {
    country_name: 'Netherlands',
    country_code: 'NL',
    flag: '🇳🇱',
  },
  {
    country_name: 'Netherlands Antilles (NL)',
    country_code: 'AN',
    flag: '🇳🇱',
  },
  {
    country_name: 'New Caledonia (FR)',
    country_code: 'NC',
    flag: '🇳🇨',
  },
  {
    country_name: 'New Zealand',
    country_code: 'NZ',
    flag: '🇳🇿',
  },
  {
    country_name: 'Nicaragua',
    country_code: 'NI',
    flag: '🇳🇮',
  },
  {
    country_name: 'Niger',
    country_code: 'NE',
    flag: '🇳🇪',
  },
  {
    country_name: 'Nigeria',
    country_code: 'NG',
    flag: '🇳🇬',
  },
  {
    country_name: 'Niue',
    country_code: 'NU',
    flag: '🇳🇺',
  },
  {
    country_name: 'Norfolk Island (AU)',
    country_code: 'NF',
    flag: '🇳🇫',
  },
  {
    country_name: 'Northern Mariana Islands (US)',
    country_code: 'MP',
    flag: '🇲🇵',
  },
  {
    country_name: 'Norway',
    country_code: 'NO',
    flag: '🇳🇴',
  },
  {
    country_name: 'Oman',
    country_code: 'OM',
    flag: '🇴🇲',
  },
  {
    country_name: 'Pakistan',
    country_code: 'PK',
    flag: '🇵🇰',
  },
  {
    country_name: 'Palestine',
    country_code: 'PS',
    flag: '🇵🇸',
  },
  {
    country_name: 'Panama',
    country_code: 'PA',
    flag: '🇵🇦',
  },
  {
    country_name: 'Papua New Guinea',
    country_code: 'PG',
    flag: '🇵🇬',
  },
  {
    country_name: 'Paraguay',
    country_code: 'PY',
    flag: '🇵🇾',
  },
  {
    country_name: 'Peru',
    country_code: 'PE',
    flag: '🇵🇪',
  },
  {
    country_name: 'Philippines',
    country_code: 'PH',
    flag: '🇵🇭',
  },
  {
    country_name: 'Pitcairn Islands (UK)',
    country_code: 'PN',
    flag: '🇵🇳',
  },
  {
    country_name: 'Poland',
    country_code: 'PL',
    flag: '🇵🇱',
  },
  {
    country_name: 'Portugal',
    country_code: 'PT',
    flag: '🇵🇹',
  },
  {
    country_name: 'Puerto Rico (US)',
    country_code: 'PR',
    flag: '🇵🇷',
  },
  {
    country_name: 'Qatar',
    country_code: 'QA',
    flag: '🇶🇦',
  },
  {
    country_name: 'Reunion (FR)',
    country_code: 'RE',
    flag: '🇷🇪',
  },
  {
    country_name: 'Romania',
    country_code: 'RO',
    flag: '🇷🇴',
  },
  {
    country_name: 'Russia',
    country_code: 'RU',
    flag: '🇷🇺',
  },
  {
    country_name: 'Rwanda',
    country_code: 'RW',
    flag: '🇷🇼',
  },
  {
    country_name: 'Saint Helena (UK)',
    country_code: 'SH',
    flag: '🇸🇭',
  },
  {
    country_name: 'Saint Kitts and Nevis',
    country_code: 'KN',
    flag: '🇰🇳',
  },
  {
    country_name: 'Saint Lucia',
    country_code: 'LC',
    flag: '🇱🇨',
  },
  {
    country_name: 'Saint Vincent and the Grenadines',
    country_code: 'VC',
    flag: '🇻🇨',
  },
  {
    country_name: 'Saint-Barthélemy',
    country_code: 'BL',
    flag: '🇧🇱',
  },
  {
    country_name: 'Saint-Martin (FR)',
    country_code: 'MF',
    flag: '🇲🇫',
  },
  {
    country_name: 'San Marino',
    country_code: 'SM',
    flag: '🇸🇲',
  },
  {
    country_name: 'Saudi Arabia',
    country_code: 'SA',
    flag: '🇸🇦',
  },
  {
    country_name: 'Senegal',
    country_code: 'SN',
    flag: '🇸🇳',
  },
  {
    country_name: 'Serbia',
    country_code: 'RS',
    flag: '🇷🇸',
  },
  {
    country_name: 'Seychelles',
    country_code: 'SC',
    flag: '🇸🇨',
  },
  {
    country_name: 'Sierra Leone',
    country_code: 'SL',
    flag: '🇸🇱',
  },
  {
    country_name: 'Singapore',
    country_code: 'SG',
    flag: '🇸🇬',
  },
  {
    country_name: 'Slovakia',
    country_code: 'SK',
    flag: '🇸🇰',
  },
  {
    country_name: 'Slovenia',
    country_code: 'SI',
    flag: '🇸🇮',
  },
  {
    country_name: 'Solomon Islands',
    country_code: 'SB',
    flag: '🇸🇧',
  },
  {
    country_name: 'Somalia',
    country_code: 'SO',
    flag: '🇸🇴',
  },
  {
    country_name: 'South Africa',
    country_code: 'ZA',
    flag: '🇿🇦',
  },
  {
    country_name: 'South Georgia & South Sandwich Islands (UK)',
    country_code: 'GS',
    flag: '🇬🇸',
  },
  {
    country_name: 'South Sudan',
    country_code: 'SS',
    flag: '🇸🇸',
  },
  {
    country_name: 'Spain',
    country_code: 'ES',
    flag: '🇪🇸',
  },
  {
    country_name: 'Sri Lanka',
    country_code: 'LK',
    flag: '🇱🇰',
  },
  {
    country_name: 'Suriname',
    country_code: 'SR',
    flag: '🇸🇷',
  },
  {
    country_name: 'Svalbard and Jan Mayen Islands',
    country_code: 'SJ',
    flag: '🇸🇯',
  },
  {
    country_name: 'Swaziland',
    country_code: 'SZ',
    flag: '🇸🇿',
  },
  {
    country_name: 'Sweden',
    country_code: 'SE',
    flag: '🇸🇪',
  },
  {
    country_name: 'Switzerland',
    country_code: 'CH',
    flag: '🇨🇭',
  },
  {
    country_name: 'Taiwan',
    country_code: 'TW',
    flag: '🇹🇼',
  },
  {
    country_name: 'Tajikistan',
    country_code: 'TJ',
    flag: '🇹🇯',
  },
  {
    country_name: 'Tanzania',
    country_code: 'TZ',
    flag: '🇹🇿',
  },
  {
    country_name: 'Thailand',
    country_code: 'TH',
    flag: '🇹🇭',
  },
  {
    country_name: 'Timor-Leste',
    country_code: 'TL',
    flag: '🇹🇱',
  },
  {
    country_name: 'Togo',
    country_code: 'TG',
    flag: '🇹🇬',
  },
  {
    country_name: 'Tokelau',
    country_code: 'TK',
    flag: '🇹🇰',
  },
  {
    country_name: 'Tonga',
    country_code: 'TO',
    flag: '🇹🇴',
  },
  {
    country_name: 'Trinidad and Tobago',
    country_code: 'TT',
    flag: '🇹🇹',
  },
  {
    country_name: 'Tunisia',
    country_code: 'TN',
    flag: '🇹🇳',
  },
  {
    country_name: 'Turkey',
    country_code: 'TR',
    flag: '🇹🇷',
  },
  {
    country_name: 'Turkmenistan',
    country_code: 'TM',
    flag: '🇹🇲',
  },
  {
    country_name: 'Turks and Caicos Islands (UK)',
    country_code: 'TC',
    flag: '🇹🇨',
  },
  {
    country_name: 'Tuvalu',
    country_code: 'TV',
    flag: '🇹🇻',
  },
  {
    country_name: 'Uganda',
    country_code: 'UG',
    flag: '🇺🇬',
  },
  {
    country_name: 'Ukraine',
    country_code: 'UA',
    flag: '🇺🇦',
  },
  {
    country_name: 'United Arab Emirates',
    country_code: 'AE',
    flag: '🇦🇪',
  },
  {
    country_name: 'United Kingdom',
    country_code: 'GB',
    flag: '🇬🇧',
  },
  {
    country_name: 'United States',
    country_code: 'US',
    flag: '🇺🇸',
  },
  {
    country_name: 'Uruguay',
    country_code: 'UY',
    flag: '🇺🇾',
  },
  {
    country_name: 'Uzbekistan',
    country_code: 'UZ',
    flag: '🇺🇿',
  },
  {
    country_name: 'Vanuatu',
    country_code: 'VU',
    flag: '🇻🇺',
  },
  {
    country_name: 'Venezuela',
    country_code: 'VE',
    flag: '🇻🇪',
  },
  {
    country_name: 'Vietnam',
    country_code: 'VN',
    flag: '🇻🇳',
  },
  {
    country_name: 'Virgin Islands (US)',
    country_code: 'VI',
    flag: '🇻🇮',
  },
  {
    country_name: 'Wallis and Futuna (FR)',
    country_code: 'WF',
    flag: '🇼🇫',
  },
  {
    country_name: 'Western Sahara',
    country_code: 'EH',
    flag: '🇪🇭',
  },
  {
    country_name: 'Yemen',
    country_code: 'YE',
    flag: '🇾🇪',
  },
  {
    country_name: 'Zambia',
    country_code: 'ZM',
    flag: '🇿🇲',
  },
  {
    country_name: 'Zimbabwe',
    country_code: 'ZW',
    flag: '🇿🇼',
  },
]
