export const CLUB_NAMES = [
  'Africa/South Africa',
  'Asia',
  'Atlantic',
  'Australia/NZ',
  'Benelux',
  'Brazil',
  'California Club',
  'Canada',
  'Carolina',
  'Celtic',
  'Central-Eastern Europe',
  'Connecticut',
  'DE-AT-CH',
  'Finland',
  'Florida',
  'France',
  'Georgia',
  'Great Plains',
  'Hispanoamérica',
  'Iberia',
  'Illinois',
  'Indiana',
  'International Club',
  'Italy',
  'Japan',
  'Massachusetts',
  'Mexico',
  'Michigan',
  'Mid-South',
  'Midwest',
  'New England',
  'New Jersey',
  'New York',
  'Northwest',
  'Ohio',
  'Pennsylvania',
  'Scandinavia',
  'Texas',
  'UK and I',
  'Virginias',
  'West',
  'Western Canada',
]

export const COUNTRIES = [
  {
    country_name_en: 'Afghanistan',
    country_name_es: 'Afganistán',
    country_code: 'AF',
    flag: '🇦🇫',
  },
  {
    country_name_en: 'Aland Islands',
    country_name_es: 'Islas Åland',
    country_code: 'AX',
    flag: '🇦🇽',
  },
  {
    country_name_en: 'Albania',
    country_name_es: 'Albania',
    country_code: 'AL',
    flag: '🇦🇱',
  },
  {
    country_name_en: 'Algeria',
    country_name_es: 'Argelia',
    country_code: 'DZ',
    flag: '🇩🇿',
  },
  {
    country_name_en: 'American Samoa (US)',
    country_name_es: 'Samoa Americana (EE. UU.)',
    country_code: 'AS',
    flag: '🇦🇸',
  },
  {
    country_name_en: 'Andorra',
    country_name_es: 'Andorra',
    country_code: 'AD',
    flag: '🇦🇩',
  },
  {
    country_name_en: 'Angola',
    country_name_es: 'Angola',
    country_code: 'AO',
    flag: '🇦🇴',
  },
  {
    country_name_en: 'Anguilla (UK)',
    country_name_es: 'Anguila (Reino Unido)',
    country_code: 'AI',
    flag: '🇦🇮',
  },
  {
    country_name_en: 'Antarctica',
    country_name_es: 'Antártida',
    country_code: 'AQ',
    flag: '🇦🇶',
  },
  {
    country_name_en: 'Antigua and Barbuda',
    country_name_es: 'Antigua y Barbuda',
    country_code: 'AG',
    flag: '🇦🇬',
  },
  {
    country_name_en: 'Argentina',
    country_name_es: 'Argentina',
    country_code: 'AR',
    flag: '🇦🇷',
  },
  {
    country_name_en: 'Armenia',
    country_name_es: 'Armenia',
    country_code: 'AM',
    flag: '🇦🇲',
  },
  {
    country_name_en: 'Aruba',
    country_name_es: 'Aruba',
    country_code: 'AW',
    flag: '🇦🇼',
  },
  {
    country_name_en: 'Australia',
    country_name_es: 'Australia',
    country_code: 'AU',
    flag: '🇦🇺',
  },
  {
    country_name_en: 'Austria',
    country_name_es: 'Austria',
    country_code: 'AT',
    flag: '🇦🇹',
  },
  {
    country_name_en: 'Azerbaijan',
    country_name_es: 'Azerbaiyán',
    country_code: 'AZ',
    flag: '🇦🇿',
  },
  {
    country_name_en: 'Bahamas',
    country_name_es: 'Bahamas',
    country_code: 'BS',
    flag: '🇧🇸',
  },
  {
    country_name_en: 'Bahrain',
    country_name_es: 'Baréin',
    country_code: 'BH',
    flag: '🇧🇭',
  },
  {
    country_name_en: 'Bangladesh',
    country_name_es: 'Bangladesh',
    country_code: 'BD',
    flag: '🇧🇩',
  },
  {
    country_name_en: 'Barbados',
    country_name_es: 'Barbados',
    country_code: 'BB',
    flag: '🇧🇧',
  },
  {
    country_name_en: 'Belarus',
    country_name_es: 'Bielorrusia',
    country_code: 'BY',
    flag: '🇧🇾',
  },
  {
    country_name_en: 'Belgium',
    country_name_es: 'Bélgica',
    country_code: 'BE',
    flag: '🇧🇪',
  },
  {
    country_name_en: 'Belize',
    country_name_es: 'Belice',
    country_code: 'BZ',
    flag: '🇧🇿',
  },
  {
    country_name_en: 'Benin',
    country_name_es: 'Benín',
    country_code: 'BJ',
    flag: '🇧🇯',
  },
  {
    country_name_en: 'Bermuda (UK)',
    country_name_es: 'Bermudas (Reino Unido)',
    country_code: 'BM',
    flag: '🇧🇲',
  },
  {
    country_name_en: 'Bhutan',
    country_name_es: 'Bután',
    country_code: 'BT',
    flag: '🇧🇹',
  },
  {
    country_name_en: 'Bolivia',
    country_name_es: 'Bolivia',
    country_code: 'BO',
    flag: '🇧🇴',
  },
  {
    country_name_en: 'Bosnia and Herzegovina',
    country_name_es: 'Bosnia y Herzegovina',
    country_code: 'BA',
    flag: '🇧🇦',
  },
  {
    country_name_en: 'Botswana',
    country_name_es: 'Botsuana',
    country_code: 'BW',
    flag: '🇧🇼',
  },
  {
    country_name_en: 'Brazil',
    country_name_es: 'Brasil',
    country_code: 'BR',
    flag: '🇧🇷',
  },
  {
    country_name_en: 'British Virgin Islands (UK)',
    country_name_es: 'Islas Vírgenes Británicas (Reino Unido)',
    country_code: 'VG',
    flag: '🇻🇬',
  },
  {
    country_name_en: 'Brunei Darussalam',
    country_name_es: 'Brunéi',
    country_code: 'BN',
    flag: '🇧🇳',
  },
  {
    country_name_en: 'Bulgaria',
    country_name_es: 'Bulgaria',
    country_code: 'BG',
    flag: '🇧🇬',
  },
  {
    country_name_en: 'Burkina Faso',
    country_name_es: 'Burkina Faso',
    country_code: 'BF',
    flag: '🇧🇫',
  },
  {
    country_name_en: 'Burundi',
    country_name_es: 'Burundi',
    country_code: 'BI',
    flag: '🇧🇮',
  },
  {
    country_name_en: 'Cambodia',
    country_name_es: 'Camboya',
    country_code: 'KH',
    flag: '🇰🇭',
  },
  {
    country_name_en: 'Cameroon',
    country_name_es: 'Camerún',
    country_code: 'CM',
    flag: '🇨🇲',
  },
  {
    country_name_en: 'Canada',
    country_name_es: 'Canadá',
    country_code: 'CA',
    flag: '🇨🇦',
  },
  {
    country_name_en: 'Cape Verde',
    country_name_es: 'Cabo Verde',
    country_code: 'CV',
    flag: '🇨🇻',
  },
  {
    country_name_en: 'Cayman Islands (UK)',
    country_name_es: 'Islas Caimán (Reino Unido)',
    country_code: 'KY',
    flag: '🇰🇾',
  },
  {
    country_name_en: 'Central African Republic',
    country_name_es: 'República Centroafricana',
    country_code: 'CF',
    flag: '🇨🇫',
  },
  {
    country_name_en: 'Chad',
    country_name_es: 'Chad',
    country_code: 'TD',
    flag: '🇹🇩',
  },
  {
    country_name_en: 'Chile',
    country_name_es: 'Chile',
    country_code: 'CL',
    flag: '🇨🇱',
  },
  {
    country_name_en: 'China',
    country_name_es: 'China',
    country_code: 'CN',
    flag: '🇨🇳',
  },
  {
    country_name_en: 'Christmas Island (AU)',
    country_name_es: 'Isla de Navidad (Australia)',
    country_code: 'CX',
    flag: '🇨🇽',
  },
  {
    country_name_en: 'Cocos (Keeling) Islands (AU)',
    country_name_es: 'Islas Cocos (Keeling) (Australia)',
    country_code: 'CC',
    flag: '🇨🇨',
  },
  {
    country_name_en: 'Colombia',
    country_name_es: 'Colombia',
    country_code: 'CO',
    flag: '🇨🇴',
  },
  {
    country_name_en: 'Congo, Democratic Republic of the',
    country_name_es: 'República Democrática del Congo',
    country_code: 'CD',
    flag: '🇨🇩',
  },
  {
    country_name_en: 'Congo, Republic of the',
    country_name_es: 'República del Congo',
    country_code: 'CG',
    flag: '🇨🇬',
  },
  {
    country_name_en: 'Costa Rica',
    country_name_es: 'Costa Rica',
    country_code: 'CR',
    flag: '🇨🇷',
  },
  {
    country_name_en: 'Croatia',
    country_name_es: 'Croacia',
    country_code: 'HR',
    flag: '🇭🇷',
  },
  {
    country_name_en: 'Cyprus',
    country_name_es: 'Chipre',
    country_code: 'CY',
    flag: '🇨🇾',
  },
  {
    country_name_en: 'Czech Republic',
    country_name_es: 'República Checa',
    country_code: 'CZ',
    flag: '🇨🇿',
  },
  {
    country_name_en: 'Denmark',
    country_name_es: 'Dinamarca',
    country_code: 'DK',
    flag: '🇩🇰',
  },
  {
    country_name_en: 'Djibouti',
    country_name_es: 'Yibuti',
    country_code: 'DJ',
    flag: '🇩🇯',
  },
  {
    country_name_en: 'Dominica',
    country_name_es: 'Dominica',
    country_code: 'DM',
    flag: '🇩🇲',
  },
  {
    country_name_en: 'Dominican Republic',
    country_name_es: 'República Dominicana',
    country_code: 'DO',
    flag: '🇩🇴',
  },
  {
    country_name_en: 'Ecuador',
    country_name_es: 'Ecuador',
    country_code: 'EC',
    flag: '🇪🇨',
  },
  {
    country_name_en: 'Egypt',
    country_name_es: 'Egipto',
    country_code: 'EG',
    flag: '🇪🇬',
  },
  {
    country_name_en: 'El Salvador',
    country_name_es: 'El Salvador',
    country_code: 'SV',
    flag: '🇸🇻',
  },
  {
    country_name_en: 'Equatorial Guinea',
    country_name_es: 'Guinea Ecuatorial',
    country_code: 'GQ',
    flag: '🇬🇶',
  },
  {
    country_name_en: 'Eritrea',
    country_name_es: 'Eritrea',
    country_code: 'ER',
    flag: '🇪🇷',
  },
  {
    country_name_en: 'Estonia',
    country_name_es: 'Estonia',
    country_code: 'EE',
    flag: '🇪🇪',
  },
  {
    country_name_en: 'Ethiopia',
    country_name_es: 'Etiopía',
    country_code: 'ET',
    flag: '🇪🇹',
  },
  {
    country_name_en: 'Falkland Islands (UK)',
    country_name_es: 'Islas Malvinas (Reino Unido)',
    country_code: 'FK',
    flag: '🇫🇰',
  },
  {
    country_name_en: 'Faroe Islands (DK)',
    country_name_es: 'Islas Feroe (Dinamarca)',
    country_code: 'FO',
    flag: '🇫🇴',
  },
  {
    country_name_en: 'Fiji',
    country_name_es: 'Fiyi',
    country_code: 'FJ',
    flag: '🇫🇯',
  },
  {
    country_name_en: 'Finland',
    country_name_es: 'Finlandia',
    country_code: 'FI',
    flag: '🇫🇮',
  },
  {
    country_name_en: 'France',
    country_name_es: 'Francia',
    country_code: 'FR',
    flag: '🇫🇷',
  },
  {
    country_name_en: 'French Guiana (FR)',
    country_name_es: 'Guayana Francesa (Francia)',
    country_code: 'GF',
    flag: '🇬🇫',
  },
  {
    country_name_en: 'French Polynesia (FR)',
    country_name_es: 'Polinesia Francesa (Francia)',
    country_code: 'PF',
    flag: '🇵🇫',
  },
  {
    country_name_en: 'Gabon',
    country_name_es: 'Gabón',
    country_code: 'GA',
    flag: '🇬🇦',
  },
  {
    country_name_en: 'Gambia',
    country_name_es: 'Gambia',
    country_code: 'GM',
    flag: '🇬🇲',
  },
  {
    country_name_en: 'Georgia',
    country_name_es: 'Georgia',
    country_code: 'GE',
    flag: '🇬🇪',
  },
  {
    country_name_en: 'Germany',
    country_name_es: 'Alemania',
    country_code: 'DE',
    flag: '🇩🇪',
  },
  {
    country_name_en: 'Ghana',
    country_name_es: 'Ghana',
    country_code: 'GH',
    flag: '🇬🇭',
  },
  {
    country_name_en: 'Gibraltar (UK)',
    country_name_es: 'Gibraltar (Reino Unido)',
    country_code: 'GI',
    flag: '🇬🇮',
  },
  {
    country_name_en: 'Greece',
    country_name_es: 'Grecia',
    country_code: 'GR',
    flag: '🇬🇷',
  },
  {
    country_name_en: 'Greenland (DK)',
    country_name_es: 'Groenlandia (Dinamarca)',
    country_code: 'GL',
    flag: '🇬🇱',
  },
  {
    country_name_en: 'Grenada',
    country_name_es: 'Granada',
    country_code: 'GD',
    flag: '🇬🇩',
  },
  {
    country_name_en: 'Guadeloupe (FR)',
    country_name_es: 'Guadalupe (Francia)',
    country_code: 'GP',
    flag: '🇬🇵',
  },
  {
    country_name_en: 'Guam (US)',
    country_name_es: 'Guam (EE. UU.)',
    country_code: 'GU',
    flag: '🇬🇺',
  },
  {
    country_name_en: 'Guatemala',
    country_name_es: 'Guatemala',
    country_code: 'GT',
    flag: '🇬🇹',
  },
  {
    country_name_en: 'Guernsey',
    country_name_es: 'Guernsey',
    country_code: 'GG',
    flag: '🇬🇬',
  },
  {
    country_name_en: 'Guinea',
    country_name_es: 'Guinea',
    country_code: 'GN',
    flag: '🇬🇳',
  },
  {
    country_name_en: 'Guinea-Bissau',
    country_name_es: 'Guinea-Bisáu',
    country_code: 'GW',
    flag: '🇬🇼',
  },
  {
    country_name_en: 'Guyana',
    country_name_es: 'Guyana',
    country_code: 'GY',
    flag: '🇬🇾',
  },
  {
    country_name_en: 'Haiti',
    country_name_es: 'Haití',
    country_code: 'HT',
    flag: '🇭🇹',
  },
  {
    country_name_en: 'Holy See (Vatican City)',
    country_name_es: 'Santa Sede (Ciudad del Vaticano)',
    country_code: 'VA',
    flag: '🇻🇦',
  },
  {
    country_name_en: 'Honduras',
    country_name_es: 'Honduras',
    country_code: 'HN',
    flag: '🇭🇳',
  },
  {
    country_name_en: 'Hong Kong (CN)',
    country_name_es: 'Hong Kong (China)',
    country_code: 'HK',
    flag: '🇭🇰',
  },
  {
    country_name_en: 'Hungary',
    country_name_es: 'Hungría',
    country_code: 'HU',
    flag: '🇭🇺',
  },
  {
    country_name_en: 'Iceland',
    country_name_es: 'Islandia',
    country_code: 'IS',
    flag: '🇮🇸',
  },
  {
    country_name_en: 'India',
    country_name_es: 'India',
    country_code: 'IN',
    flag: '🇮🇳',
  },
  {
    country_name_en: 'Indonesia',
    country_name_es: 'Indonesia',
    country_code: 'ID',
    flag: '🇮🇩',
  },
  {
    country_name_en: 'Iraq',
    country_name_es: 'Irak',
    country_code: 'IQ',
    flag: '🇮🇶',
  },
  {
    country_name_en: 'Ireland',
    country_name_es: 'Irlanda',
    country_code: 'IE',
    flag: '🇮🇪',
  },
  {
    country_name_en: 'Isle of Man',
    country_name_es: 'Isla de Man',
    country_code: 'IM',
    flag: '🇮🇲',
  },
  {
    country_name_en: 'Israel',
    country_name_es: 'Israel',
    country_code: 'IL',
    flag: '🇮🇱',
  },
  {
    country_name_en: 'Italy',
    country_name_es: 'Italia',
    country_code: 'IT',
    flag: '🇮🇹',
  },
  {
    country_name_en: 'Ivory Coast',
    country_name_es: 'Costa de Marfil',
    country_code: 'CI',
    flag: '🇨🇮',
  },
  {
    country_name_en: 'Jamaica',
    country_name_es: 'Jamaica',
    country_code: 'JM',
    flag: '🇯🇲',
  },
  {
    country_name_en: 'Japan',
    country_name_es: 'Japón',
    country_code: 'JP',
    flag: '🇯🇵',
  },
  {
    country_name_en: 'Jersey, Island of',
    country_name_es: 'Jersey',
    country_code: 'JE',
    flag: '🇯🇪',
  },
  {
    country_name_en: 'Jordan',
    country_name_es: 'Jordania',
    country_code: 'JO',
    flag: '🇯🇴',
  },
  {
    country_name_en: 'Kazakhstan',
    country_name_es: 'Kazajistán',
    country_code: 'KZ',
    flag: '🇰🇿',
  },
  {
    country_name_en: 'Kenya',
    country_name_es: 'Kenia',
    country_code: 'KE',
    flag: '🇰🇪',
  },
  {
    country_name_en: 'Korea - Republic of (South)',
    country_name_es: 'Corea del Sur',
    country_code: 'KR',
    flag: '🇰🇷',
  },
  {
    country_name_en: 'Kuwait',
    country_name_es: 'Kuwait',
    country_code: 'KW',
    flag: '🇰🇼',
  },
  {
    country_name_en: 'Kyrgyzstan',
    country_name_es: 'Kirguistán',
    country_code: 'KG',
    flag: '🇰🇬',
  },
  {
    country_name_en: 'Laos',
    country_name_es: 'Laos',
    country_code: 'LA',
    flag: '🇱🇦',
  },
  {
    country_name_en: 'Latvia',
    country_name_es: 'Letonia',
    country_code: 'LV',
    flag: '🇱🇻',
  },
  {
    country_name_en: 'Lebanon',
    country_name_es: 'Líbano',
    country_code: 'LB',
    flag: '🇱🇧',
  },
  {
    country_name_en: 'Lesotho',
    country_name_es: 'Lesoto',
    country_code: 'LS',
    flag: '🇱🇸',
  },
  {
    country_name_en: 'Libya',
    country_name_es: 'Libia',
    country_code: 'LY',
    flag: '🇱🇾',
  },
  {
    country_name_en: 'Liechtenstein',
    country_name_es: 'Liechtenstein',
    country_code: 'LI',
    flag: '🇱🇮',
  },
  {
    country_name_en: 'Lithuania',
    country_name_es: 'Lituania',
    country_code: 'LT',
    flag: '🇱🇹',
  },
  {
    country_name_en: 'Luxembourg',
    country_name_es: 'Luxemburgo',
    country_code: 'LU',
    flag: '🇱🇺',
  },
  {
    country_name_en: 'Macau (CN)',
    country_name_es: 'Macao (China)',
    country_code: 'MO',
    flag: '🇲🇴',
  },
  {
    country_name_en: 'Macedonia',
    country_name_es: 'Macedonia del Norte',
    country_code: 'MK',
    flag: '🇲🇰',
  },
  {
    country_name_en: 'Madagascar',
    country_name_es: 'Madagascar',
    country_code: 'MG',
    flag: '🇲🇬',
  },
  {
    country_name_en: 'Malawi',
    country_name_es: 'Malaui',
    country_code: 'MW',
    flag: '🇲🇼',
  },
  {
    country_name_en: 'Malaysia',
    country_name_es: 'Malasia',
    country_code: 'MY',
    flag: '🇲🇾',
  },
  {
    country_name_en: 'Maldives',
    country_name_es: 'Maldivas',
    country_code: 'MV',
    flag: '🇲🇻',
  },
  {
    country_name_en: 'Mali',
    country_name_es: 'Malí',
    country_code: 'ML',
    flag: '🇲🇱',
  },
  {
    country_name_en: 'Malta',
    country_name_es: 'Malta',
    country_code: 'MT',
    flag: '🇲🇹',
  },
  {
    country_name_en: 'Marshall Islands',
    country_name_es: 'Islas Marshall',
    country_code: 'MH',
    flag: '🇲🇭',
  },
  {
    country_name_en: 'Martinique (FR)',
    country_name_es: 'Martinica (Francia)',
    country_code: 'MQ',
    flag: '🇲🇶',
  },
  {
    country_name_en: 'Mauritania',
    country_name_es: 'Mauritania',
    country_code: 'MR',
    flag: '🇲🇷',
  },
  {
    country_name_en: 'Mauritius',
    country_name_es: 'Mauricio',
    country_code: 'MU',
    flag: '🇲🇺',
  },
  {
    country_name_en: 'Mayotte (FR)',
    country_name_es: 'Mayotte (Francia)',
    country_code: 'YT',
    flag: '🇾🇹',
  },
  {
    country_name_en: 'Mexico',
    country_name_es: 'México',
    country_code: 'MX',
    flag: '🇲🇽',
  },
  {
    country_name_en: 'Micronesia, Federated States of',
    country_name_es: 'Micronesia',
    country_code: 'FM',
    flag: '🇫🇲',
  },
  {
    country_name_en: 'Moldova Republic of',
    country_name_es: 'Moldavia',
    country_code: 'MD',
    flag: '🇲🇩',
  },
  {
    country_name_en: 'Monaco',
    country_name_es: 'Mónaco',
    country_code: 'MC',
    flag: '🇲🇨',
  },
  {
    country_name_en: 'Mongolia',
    country_name_es: 'Mongolia',
    country_code: 'MN',
    flag: '🇲🇳',
  },
  {
    country_name_en: 'Montenegro',
    country_name_es: 'Montenegro',
    country_code: 'ME',
    flag: '🇲🇪',
  },
  {
    country_name_en: 'Montserrat (UK)',
    country_name_es: 'Montserrat (Reino Unido)',
    country_code: 'MS',
    flag: '🇲🇸',
  },
  {
    country_name_en: 'Morocco',
    country_name_es: 'Marruecos',
    country_code: 'MA',
    flag: '🇲🇦',
  },
  {
    country_name_en: 'Mozambique',
    country_name_es: 'Mozambique',
    country_code: 'MZ',
    flag: '🇲🇿',
  },
  {
    country_name_en: 'Myanmar',
    country_name_es: 'Myanmar (Birmania)',
    country_code: 'MM',
    flag: '🇲🇲',
  },
  {
    country_name_en: 'Namibia',
    country_name_es: 'Namibia',
    country_code: 'NA',
    flag: '🇳🇦',
  },
  {
    country_name_en: 'Nepal',
    country_name_es: 'Nepal',
    country_code: 'NP',
    flag: '🇳🇵',
  },
  {
    country_name_en: 'Netherlands',
    country_name_es: 'Países Bajos',
    country_code: 'NL',
    flag: '🇳🇱',
  },
  {
    country_name_en: 'Netherlands Antilles (NL)',
    country_name_es: 'Antillas Neerlandesas',
    country_code: 'AN',
    flag: '🇳🇱',
  },
  {
    country_name_en: 'New Caledonia (FR)',
    country_name_es: 'Nueva Caledonia (Francia)',
    country_code: 'NC',
    flag: '🇳🇨',
  },
  {
    country_name_en: 'New Zealand',
    country_name_es: 'Nueva Zelanda',
    country_code: 'NZ',
    flag: '🇳🇿',
  },
  {
    country_name_en: 'Nicaragua',
    country_name_es: 'Nicaragua',
    country_code: 'NI',
    flag: '🇳🇮',
  },
  {
    country_name_en: 'Niger',
    country_name_es: 'Níger',
    country_code: 'NE',
    flag: '🇳🇪',
  },
  {
    country_name_en: 'Nigeria',
    country_name_es: 'Nigeria',
    country_code: 'NG',
    flag: '🇳🇬',
  },
  {
    country_name_en: 'Niue',
    country_name_es: 'Niue',
    country_code: 'NU',
    flag: '🇳🇺',
  },
  {
    country_name_en: 'Norfolk Island (AU)',
    country_name_es: 'Isla Norfolk (Australia)',
    country_code: 'NF',
    flag: '🇳🇫',
  },
  {
    country_name_en: 'Northern Mariana Islands (US)',
    country_name_es: 'Islas Marianas del Norte (EE. UU.)',
    country_code: 'MP',
    flag: '🇲🇵',
  },
  {
    country_name_en: 'Norway',
    country_name_es: 'Noruega',
    country_code: 'NO',
    flag: '🇳🇴',
  },
  {
    country_name_en: 'Oman',
    country_name_es: 'Omán',
    country_code: 'OM',
    flag: '🇴🇲',
  },
  {
    country_name_en: 'Pakistan',
    country_name_es: 'Pakistán',
    country_code: 'PK',
    flag: '🇵🇰',
  },
  {
    country_name_en: 'Palestine',
    country_name_es: 'Palestina',
    country_code: 'PS',
    flag: '🇵🇸',
  },
  {
    country_name_en: 'Panama',
    country_name_es: 'Panamá',
    country_code: 'PA',
    flag: '🇵🇦',
  },
  {
    country_name_en: 'Papua New Guinea',
    country_name_es: 'Papúa Nueva Guinea',
    country_code: 'PG',
    flag: '🇵🇬',
  },
  {
    country_name_en: 'Paraguay',
    country_name_es: 'Paraguay',
    country_code: 'PY',
    flag: '🇵🇾',
  },
  {
    country_name_en: 'Peru',
    country_name_es: 'Perú',
    country_code: 'PE',
    flag: '🇵🇪',
  },
  {
    country_name_en: 'Philippines',
    country_name_es: 'Filipinas',
    country_code: 'PH',
    flag: '🇵🇭',
  },
  {
    country_name_en: 'Pitcairn Islands (UK)',
    country_name_es: 'Islas Pitcairn (Reino Unido)',
    country_code: 'PN',
    flag: '🇵🇳',
  },
  {
    country_name_en: 'Poland',
    country_name_es: 'Polonia',
    country_code: 'PL',
    flag: '🇵🇱',
  },
  {
    country_name_en: 'Portugal',
    country_name_es: 'Portugal',
    country_code: 'PT',
    flag: '🇵🇹',
  },
  {
    country_name_en: 'Puerto Rico (US)',
    country_name_es: 'Puerto Rico (EE. UU.)',
    country_code: 'PR',
    flag: '🇵🇷',
  },
  {
    country_name_en: 'Qatar',
    country_name_es: 'Catar',
    country_code: 'QA',
    flag: '🇶🇦',
  },
  {
    country_name_en: 'Reunion (FR)',
    country_name_es: 'Reunión (Francia)',
    country_code: 'RE',
    flag: '🇷🇪',
  },
  {
    country_name_en: 'Romania',
    country_name_es: 'Rumania',
    country_code: 'RO',
    flag: '🇷🇴',
  },
  {
    country_name_en: 'Russia',
    country_name_es: 'Rusia',
    country_code: 'RU',
    flag: '🇷🇺',
  },
  {
    country_name_en: 'Rwanda',
    country_name_es: 'Ruanda',
    country_code: 'RW',
    flag: '🇷🇼',
  },
  {
    country_name_en: 'Saint Helena (UK)',
    country_name_es: 'Santa Elena (Reino Unido)',
    country_code: 'SH',
    flag: '🇸🇭',
  },
  {
    country_name_en: 'Saint Kitts and Nevis',
    country_name_es: 'San Cristóbal y Nieves',
    country_code: 'KN',
    flag: '🇰🇳',
  },
  {
    country_name_en: 'Saint Lucia',
    country_name_es: 'Santa Lucía',
    country_code: 'LC',
    flag: '🇱🇨',
  },
  {
    country_name_en: 'Saint Vincent and the Grenadines',
    country_name_es: 'San Vicente y las Granadinas',
    country_code: 'VC',
    flag: '🇻🇨',
  },
  {
    country_name_en: 'Saint-Barthélemy',
    country_name_es: 'San Bartolomé',
    country_code: 'BL',
    flag: '🇧🇱',
  },
  {
    country_name_en: 'Saint-Martin (FR)',
    country_name_es: 'San Martín (Francia)',
    country_code: 'MF',
    flag: '🇲🇫',
  },
  {
    country_name_en: 'San Marino',
    country_name_es: 'San Marino',
    country_code: 'SM',
    flag: '🇸🇲',
  },
  {
    country_name_en: 'Saudi Arabia',
    country_name_es: 'Arabia Saudita',
    country_code: 'SA',
    flag: '🇸🇦',
  },
  {
    country_name_en: 'Senegal',
    country_name_es: 'Senegal',
    country_code: 'SN',
    flag: '🇸🇳',
  },
  {
    country_name_en: 'Serbia',
    country_name_es: 'Serbia',
    country_code: 'RS',
    flag: '🇷🇸',
  },
  {
    country_name_en: 'Seychelles',
    country_name_es: 'Seychelles',
    country_code: 'SC',
    flag: '🇸🇨',
  },
  {
    country_name_en: 'Sierra Leone',
    country_name_es: 'Sierra Leona',
    country_code: 'SL',
    flag: '🇸🇱',
  },
  {
    country_name_en: 'Singapore',
    country_name_es: 'Singapur',
    country_code: 'SG',
    flag: '🇸🇬',
  },
  {
    country_name_en: 'Slovakia',
    country_name_es: 'Eslovaquia',
    country_code: 'SK',
    flag: '🇸🇰',
  },
  {
    country_name_en: 'Slovenia',
    country_name_es: 'Eslovenia',
    country_code: 'SI',
    flag: '🇸🇮',
  },
  {
    country_name_en: 'Solomon Islands',
    country_name_es: 'Islas Salomón',
    country_code: 'SB',
    flag: '🇸🇧',
  },
  {
    country_name_en: 'Somalia',
    country_name_es: 'Somalia',
    country_code: 'SO',
    flag: '🇸🇴',
  },
  {
    country_name_en: 'South Africa',
    country_name_es: 'Sudáfrica',
    country_code: 'ZA',
    flag: '🇿🇦',
  },
  {
    country_name_en: 'South Georgia & South Sandwich Islands (UK)',
    country_name_es: 'Islas Georgias del Sur y Sandwich del Sur (Reino Unido)',
    country_code: 'GS',
    flag: '🇬🇸',
  },
  {
    country_name_en: 'South Sudan',
    country_name_es: 'Sudán del Sur',
    country_code: 'SS',
    flag: '🇸🇸',
  },
  {
    country_name_en: 'Spain',
    country_name_es: 'España',
    country_code: 'ES',
    flag: '🇪🇸',
  },
  {
    country_name_en: 'Sri Lanka',
    country_name_es: 'Sri Lanka',
    country_code: 'LK',
    flag: '🇱🇰',
  },
  {
    country_name_en: 'Suriname',
    country_name_es: 'Surinam',
    country_code: 'SR',
    flag: '🇸🇷',
  },
  {
    country_name_en: 'Svalbard and Jan Mayen Islands',
    country_name_es: 'Svalbard y Jan Mayen',
    country_code: 'SJ',
    flag: '🇸🇯',
  },
  {
    country_name_en: 'Swaziland',
    country_name_es: 'Esuatini',
    country_code: 'SZ',
    flag: '🇸🇿',
  },
  {
    country_name_en: 'Sweden',
    country_name_es: 'Suecia',
    country_code: 'SE',
    flag: '🇸🇪',
  },
  {
    country_name_en: 'Switzerland',
    country_name_es: 'Suiza',
    country_code: 'CH',
    flag: '🇨🇭',
  },
  {
    country_name_en: 'Taiwan',
    country_name_es: 'Taiwán',
    country_code: 'TW',
    flag: '🇹🇼',
  },
  {
    country_name_en: 'Tajikistan',
    country_name_es: 'Tayikistán',
    country_code: 'TJ',
    flag: '🇹🇯',
  },
  {
    country_name_en: 'Tanzania',
    country_name_es: 'Tanzania',
    country_code: 'TZ',
    flag: '🇹🇿',
  },
  {
    country_name_en: 'Thailand',
    country_name_es: 'Tailandia',
    country_code: 'TH',
    flag: '🇹🇭',
  },
  {
    country_name_en: 'Timor-Leste',
    country_name_es: 'Timor Oriental',
    country_code: 'TL',
    flag: '🇹🇱',
  },
  {
    country_name_en: 'Togo',
    country_name_es: 'Togo',
    country_code: 'TG',
    flag: '🇹🇬',
  },
  {
    country_name_en: 'Tokelau',
    country_name_es: 'Tokelau',
    country_code: 'TK',
    flag: '🇹🇰',
  },
  {
    country_name_en: 'Tonga',
    country_name_es: 'Tonga',
    country_code: 'TO',
    flag: '🇹🇴',
  },
  {
    country_name_en: 'Trinidad and Tobago',
    country_name_es: 'Trinidad y Tobago',
    country_code: 'TT',
    flag: '🇹🇹',
  },
  {
    country_name_en: 'Tunisia',
    country_name_es: 'Túnez',
    country_code: 'TN',
    flag: '🇹🇳',
  },
  {
    country_name_en: 'Turkey',
    country_name_es: 'Turquía',
    country_code: 'TR',
    flag: '🇹🇷',
  },
  {
    country_name_en: 'Turkmenistan',
    country_name_es: 'Turkmenistán',
    country_code: 'TM',
    flag: '🇹🇲',
  },
  {
    country_name_en: 'Turks and Caicos Islands (UK)',
    country_name_es: 'Islas Turcas y Caicos (Reino Unido)',
    country_code: 'TC',
    flag: '🇹🇨',
  },
  {
    country_name_en: 'Tuvalu',
    country_name_es: 'Tuvalu',
    country_code: 'TV',
    flag: '🇹🇻',
  },
  {
    country_name_en: 'Uganda',
    country_name_es: 'Uganda',
    country_code: 'UG',
    flag: '🇺🇬',
  },
  {
    country_name_en: 'Ukraine',
    country_name_es: 'Ucrania',
    country_code: 'UA',
    flag: '🇺🇦',
  },
  {
    country_name_en: 'United Arab Emirates',
    country_name_es: 'Emiratos Árabes Unidos',
    country_code: 'AE',
    flag: '🇦🇪',
  },
  {
    country_name_en: 'United Kingdom',
    country_name_es: 'Reino Unido',
    country_code: 'GB',
    flag: '🇬🇧',
  },
  {
    country_name_en: 'United States',
    country_name_es: 'Estados Unidos',
    country_code: 'US',
    flag: '🇺🇸',
  },
  {
    country_name_en: 'Uruguay',
    country_name_es: 'Uruguay',
    country_code: 'UY',
    flag: '🇺🇾',
  },
  {
    country_name_en: 'Uzbekistan',
    country_name_es: 'Uzbekistán',
    country_code: 'UZ',
    flag: '🇺🇿',
  },
  {
    country_name_en: 'Vanuatu',
    country_name_es: 'Vanuatu',
    country_code: 'VU',
    flag: '🇻🇺',
  },
  {
    country_name_en: 'Venezuela',
    country_name_es: 'Venezuela',
    country_code: 'VE',
    flag: '🇻🇪',
  },
  {
    country_name_en: 'Vietnam',
    country_name_es: 'Vietnam',
    country_code: 'VN',
    flag: '🇻🇳',
  },
  {
    country_name_en: 'Virgin Islands (US)',
    country_name_es: 'Islas Vírgenes (EE. UU.)',
    country_code: 'VI',
    flag: '🇻🇮',
  },
  {
    country_name_en: 'Wallis and Futuna (FR)',
    country_name_es: 'Wallis y Futuna (Francia)',
    country_code: 'WF',
    flag: '🇼🇫',
  },
  {
    country_name_en: 'Western Sahara',
    country_name_es: 'Sahara Occidental',
    country_code: 'EH',
    flag: '🇪🇭',
  },
  {
    country_name_en: 'Yemen',
    country_name_es: 'Yemen',
    country_code: 'YE',
    flag: '🇾🇪',
  },
  {
    country_name_en: 'Zambia',
    country_name_es: 'Zambia',
    country_code: 'ZM',
    flag: '🇿🇲',
  },
  {
    country_name_en: 'Zimbabwe',
    country_name_es: 'Zimbabue',
    country_code: 'ZW',
    flag: '🇿🇼',
  },
]

export const LICENSES = [
  {
    license_letter: 'R',
    license_name_en: 'Rookie',
    license_name_es: 'Novato',
    license_color: 'red',
  },
  {
    license_letter: 'D',
    license_name_en: 'Class D',
    license_name_es: 'Clase D',
    license_color: 'orange',
  },
  {
    license_letter: 'C',
    license_name_en: 'Class C',
    license_name_es: 'Clase C',
    license_color: 'yellow',
  },
  {
    license_letter: 'B',
    license_name_en: 'Class B',
    license_name_es: 'Clase B',
    license_color: 'green',
  },
  {
    license_letter: 'A',
    license_name_en: 'Class A',
    license_name_es: 'Clase A',
    license_color: 'blue',
  },
  {
    license_letter: 'P',
    license_name_en: 'Pro / WC',
    license_name_es: 'Pro / CM',
    license_color: 'gray',
  },
]

export const CATEGORIES = [
  {
    category_name_en: 'Sports Cars',
    category_name_es: 'Deportivos',
    category_code: 'sports-cars',
    category_table_name: 'driver-stats-sports_car',
  },
  {
    category_name_en: 'Formula Cars',
    category_name_es: 'Monoplazas',
    category_code: 'formula-cars',
    category_table_name: 'driver-stats-formula_car',
  },
  {
    category_name_en: 'Oval',
    category_name_es: 'Óvalos',
    category_code: 'oval',
    category_table_name: 'driver-stats-oval',
  },
  {
    category_name_en: 'Dirt Oval',
    category_name_es: 'Óvalos de Tierra',
    category_code: 'dirt-oval',
    category_table_name: 'driver-stats-dirt_oval',
  },
  {
    category_name_en: 'Dirt Road',
    category_name_es: 'Circuitos de Tierra',
    category_code: 'dirt-road',
    category_table_name: 'driver-stats-dirt_road',
  },
]
