export const CLUB_NAMES = [
  'Africa/South Africa',
  'Asia',
  'Atlantic',
  'Australia/NZ',
  'Benelux',
  'Brazil',
  'California Club',
  'Canada',
  'Carolina',
  'Celtic',
  'Central-Eastern Europe',
  'Connecticut',
  'DE-AT-CH',
  'Finland',
  'Florida',
  'France',
  'Georgia',
  'Great Plains',
  'Hispanoamérica',
  'Iberia',
  'Illinois',
  'Indiana',
  'International Club',
  'Italy',
  'Japan',
  'Massachusetts',
  'Mexico',
  'Michigan',
  'Mid-South',
  'Midwest',
  'New England',
  'New Jersey',
  'New York',
  'Northwest',
  'Ohio',
  'Pennsylvania',
  'Scandinavia',
  'Texas',
  'UK and I',
  'Virginias',
  'West',
  'Western Canada',
]

export const COUNTRIES = [
  {
    country_name_en: 'Afghanistan',
    country_name_es: 'Afganistán',
    country_code: 'AF',
  },
  {
    country_name_en: 'Aland Islands',
    country_name_es: 'Islas Åland',
    country_code: 'AX',
  },
  {
    country_name_en: 'Albania',
    country_name_es: 'Albania',
    country_code: 'AL',
  },
  {
    country_name_en: 'Algeria',
    country_name_es: 'Argelia',
    country_code: 'DZ',
  },
  {
    country_name_en: 'American Samoa (US)',
    country_name_es: 'Samoa Americana (EE. UU.)',
    country_code: 'AS',
  },
  {
    country_name_en: 'Andorra',
    country_name_es: 'Andorra',
    country_code: 'AD',
  },
  {
    country_name_en: 'Angola',
    country_name_es: 'Angola',
    country_code: 'AO',
  },
  {
    country_name_en: 'Anguilla (UK)',
    country_name_es: 'Anguila (Reino Unido)',
    country_code: 'AI',
  },
  {
    country_name_en: 'Antarctica',
    country_name_es: 'Antártida',
    country_code: 'AQ',
  },
  {
    country_name_en: 'Antigua and Barbuda',
    country_name_es: 'Antigua y Barbuda',
    country_code: 'AG',
  },
  {
    country_name_en: 'Argentina',
    country_name_es: 'Argentina',
    country_code: 'AR',
  },
  {
    country_name_en: 'Armenia',
    country_name_es: 'Armenia',
    country_code: 'AM',
  },
  {
    country_name_en: 'Aruba',
    country_name_es: 'Aruba',
    country_code: 'AW',
  },
  {
    country_name_en: 'Australia',
    country_name_es: 'Australia',
    country_code: 'AU',
  },
  {
    country_name_en: 'Austria',
    country_name_es: 'Austria',
    country_code: 'AT',
  },
  {
    country_name_en: 'Azerbaijan',
    country_name_es: 'Azerbaiyán',
    country_code: 'AZ',
  },
  {
    country_name_en: 'Bahamas',
    country_name_es: 'Bahamas',
    country_code: 'BS',
  },
  {
    country_name_en: 'Bahrain',
    country_name_es: 'Baréin',
    country_code: 'BH',
  },
  {
    country_name_en: 'Bangladesh',
    country_name_es: 'Bangladesh',
    country_code: 'BD',
  },
  {
    country_name_en: 'Barbados',
    country_name_es: 'Barbados',
    country_code: 'BB',
  },
  {
    country_name_en: 'Belarus',
    country_name_es: 'Bielorrusia',
    country_code: 'BY',
  },
  {
    country_name_en: 'Belgium',
    country_name_es: 'Bélgica',
    country_code: 'BE',
  },
  {
    country_name_en: 'Belize',
    country_name_es: 'Belice',
    country_code: 'BZ',
  },
  {
    country_name_en: 'Benin',
    country_name_es: 'Benín',
    country_code: 'BJ',
  },
  {
    country_name_en: 'Bermuda (UK)',
    country_name_es: 'Bermudas (Reino Unido)',
    country_code: 'BM',
  },
  {
    country_name_en: 'Bhutan',
    country_name_es: 'Bután',
    country_code: 'BT',
  },
  {
    country_name_en: 'Bolivia',
    country_name_es: 'Bolivia',
    country_code: 'BO',
  },
  {
    country_name_en: 'Bosnia and Herzegovina',
    country_name_es: 'Bosnia y Herzegovina',
    country_code: 'BA',
  },
  {
    country_name_en: 'Botswana',
    country_name_es: 'Botsuana',
    country_code: 'BW',
  },
  {
    country_name_en: 'Brazil',
    country_name_es: 'Brasil',
    country_code: 'BR',
  },
  {
    country_name_en: 'British Virgin Islands (UK)',
    country_name_es: 'Islas Vírgenes Británicas (Reino Unido)',
    country_code: 'VG',
  },
  {
    country_name_en: 'Brunei Darussalam',
    country_name_es: 'Brunéi',
    country_code: 'BN',
  },
  {
    country_name_en: 'Bulgaria',
    country_name_es: 'Bulgaria',
    country_code: 'BG',
  },
  {
    country_name_en: 'Burkina Faso',
    country_name_es: 'Burkina Faso',
    country_code: 'BF',
  },
  {
    country_name_en: 'Burundi',
    country_name_es: 'Burundi',
    country_code: 'BI',
  },
  {
    country_name_en: 'Cambodia',
    country_name_es: 'Camboya',
    country_code: 'KH',
  },
  {
    country_name_en: 'Cameroon',
    country_name_es: 'Camerún',
    country_code: 'CM',
  },
  {
    country_name_en: 'Canada',
    country_name_es: 'Canadá',
    country_code: 'CA',
  },
  {
    country_name_en: 'Cape Verde',
    country_name_es: 'Cabo Verde',
    country_code: 'CV',
  },
  {
    country_name_en: 'Cayman Islands (UK)',
    country_name_es: 'Islas Caimán (Reino Unido)',
    country_code: 'KY',
  },
  {
    country_name_en: 'Central African Republic',
    country_name_es: 'República Centroafricana',
    country_code: 'CF',
  },
  {
    country_name_en: 'Chad',
    country_name_es: 'Chad',
    country_code: 'TD',
  },
  {
    country_name_en: 'Chile',
    country_name_es: 'Chile',
    country_code: 'CL',
  },
  {
    country_name_en: 'China',
    country_name_es: 'China',
    country_code: 'CN',
  },
  {
    country_name_en: 'Christmas Island (AU)',
    country_name_es: 'Isla de Navidad (Australia)',
    country_code: 'CX',
  },
  {
    country_name_en: 'Cocos (Keeling) Islands (AU)',
    country_name_es: 'Islas Cocos (Keeling) (Australia)',
    country_code: 'CC',
  },
  {
    country_name_en: 'Colombia',
    country_name_es: 'Colombia',
    country_code: 'CO',
  },
  {
    country_name_en: 'Congo, Democratic Republic of the',
    country_name_es: 'República Democrática del Congo',
    country_code: 'CD',
  },
  {
    country_name_en: 'Congo, Republic of the',
    country_name_es: 'República del Congo',
    country_code: 'CG',
  },
  {
    country_name_en: 'Costa Rica',
    country_name_es: 'Costa Rica',
    country_code: 'CR',
  },
  {
    country_name_en: 'Croatia',
    country_name_es: 'Croacia',
    country_code: 'HR',
  },
  {
    country_name_en: 'Cyprus',
    country_name_es: 'Chipre',
    country_code: 'CY',
  },
  {
    country_name_en: 'Czech Republic',
    country_name_es: 'República Checa',
    country_code: 'CZ',
  },
  {
    country_name_en: 'Denmark',
    country_name_es: 'Dinamarca',
    country_code: 'DK',
  },
  {
    country_name_en: 'Djibouti',
    country_name_es: 'Yibuti',
    country_code: 'DJ',
  },
  {
    country_name_en: 'Dominica',
    country_name_es: 'Dominica',
    country_code: 'DM',
  },
  {
    country_name_en: 'Dominican Republic',
    country_name_es: 'República Dominicana',
    country_code: 'DO',
  },
  {
    country_name_en: 'Ecuador',
    country_name_es: 'Ecuador',
    country_code: 'EC',
  },
  {
    country_name_en: 'Egypt',
    country_name_es: 'Egipto',
    country_code: 'EG',
  },
  {
    country_name_en: 'El Salvador',
    country_name_es: 'El Salvador',
    country_code: 'SV',
  },
  {
    country_name_en: 'Equatorial Guinea',
    country_name_es: 'Guinea Ecuatorial',
    country_code: 'GQ',
  },
  {
    country_name_en: 'Eritrea',
    country_name_es: 'Eritrea',
    country_code: 'ER',
  },
  {
    country_name_en: 'Estonia',
    country_name_es: 'Estonia',
    country_code: 'EE',
  },
  {
    country_name_en: 'Ethiopia',
    country_name_es: 'Etiopía',
    country_code: 'ET',
  },
  {
    country_name_en: 'Falkland Islands (UK)',
    country_name_es: 'Islas Malvinas (Reino Unido)',
    country_code: 'FK',
  },
  {
    country_name_en: 'Faroe Islands (DK)',
    country_name_es: 'Islas Feroe (Dinamarca)',
    country_code: 'FO',
  },
  {
    country_name_en: 'Fiji',
    country_name_es: 'Fiyi',
    country_code: 'FJ',
  },
  {
    country_name_en: 'Finland',
    country_name_es: 'Finlandia',
    country_code: 'FI',
  },
  {
    country_name_en: 'France',
    country_name_es: 'Francia',
    country_code: 'FR',
  },
  {
    country_name_en: 'French Guiana (FR)',
    country_name_es: 'Guayana Francesa (Francia)',
    country_code: 'GF',
  },
  {
    country_name_en: 'French Polynesia (FR)',
    country_name_es: 'Polinesia Francesa (Francia)',
    country_code: 'PF',
  },
  {
    country_name_en: 'Gabon',
    country_name_es: 'Gabón',
    country_code: 'GA',
  },
  {
    country_name_en: 'Gambia',
    country_name_es: 'Gambia',
    country_code: 'GM',
  },
  {
    country_name_en: 'Georgia',
    country_name_es: 'Georgia',
    country_code: 'GE',
  },
  {
    country_name_en: 'Germany',
    country_name_es: 'Alemania',
    country_code: 'DE',
  },
  {
    country_name_en: 'Ghana',
    country_name_es: 'Ghana',
    country_code: 'GH',
  },
  {
    country_name_en: 'Gibraltar (UK)',
    country_name_es: 'Gibraltar (Reino Unido)',
    country_code: 'GI',
  },
  {
    country_name_en: 'Greece',
    country_name_es: 'Grecia',
    country_code: 'GR',
  },
  {
    country_name_en: 'Greenland (DK)',
    country_name_es: 'Groenlandia (Dinamarca)',
    country_code: 'GL',
  },
  {
    country_name_en: 'Grenada',
    country_name_es: 'Granada',
    country_code: 'GD',
  },
  {
    country_name_en: 'Guadeloupe (FR)',
    country_name_es: 'Guadalupe (Francia)',
    country_code: 'GP',
  },
  {
    country_name_en: 'Guam (US)',
    country_name_es: 'Guam (EE. UU.)',
    country_code: 'GU',
  },
  {
    country_name_en: 'Guatemala',
    country_name_es: 'Guatemala',
    country_code: 'GT',
  },
  {
    country_name_en: 'Guernsey',
    country_name_es: 'Guernsey',
    country_code: 'GG',
  },
  {
    country_name_en: 'Guinea',
    country_name_es: 'Guinea',
    country_code: 'GN',
  },
  {
    country_name_en: 'Guinea-Bissau',
    country_name_es: 'Guinea-Bisáu',
    country_code: 'GW',
  },
  {
    country_name_en: 'Guyana',
    country_name_es: 'Guyana',
    country_code: 'GY',
  },
  {
    country_name_en: 'Haiti',
    country_name_es: 'Haití',
    country_code: 'HT',
  },
  {
    country_name_en: 'Holy See (Vatican City)',
    country_name_es: 'Santa Sede (Ciudad del Vaticano)',
    country_code: 'VA',
  },
  {
    country_name_en: 'Honduras',
    country_name_es: 'Honduras',
    country_code: 'HN',
  },
  {
    country_name_en: 'Hong Kong (CN)',
    country_name_es: 'Hong Kong (China)',
    country_code: 'HK',
  },
  {
    country_name_en: 'Hungary',
    country_name_es: 'Hungría',
    country_code: 'HU',
  },
  {
    country_name_en: 'Iceland',
    country_name_es: 'Islandia',
    country_code: 'IS',
  },
  {
    country_name_en: 'India',
    country_name_es: 'India',
    country_code: 'IN',
  },
  {
    country_name_en: 'Indonesia',
    country_name_es: 'Indonesia',
    country_code: 'ID',
  },
  {
    country_name_en: 'Iraq',
    country_name_es: 'Irak',
    country_code: 'IQ',
  },
  {
    country_name_en: 'Ireland',
    country_name_es: 'Irlanda',
    country_code: 'IE',
  },
  {
    country_name_en: 'Isle of Man',
    country_name_es: 'Isla de Man',
    country_code: 'IM',
  },
  {
    country_name_en: 'Israel',
    country_name_es: 'Israel',
    country_code: 'IL',
  },
  {
    country_name_en: 'Italy',
    country_name_es: 'Italia',
    country_code: 'IT',
  },
  {
    country_name_en: 'Ivory Coast',
    country_name_es: 'Costa de Marfil',
    country_code: 'CI',
  },
  {
    country_name_en: 'Jamaica',
    country_name_es: 'Jamaica',
    country_code: 'JM',
  },
  {
    country_name_en: 'Japan',
    country_name_es: 'Japón',
    country_code: 'JP',
  },
  {
    country_name_en: 'Jersey, Island of',
    country_name_es: 'Jersey',
    country_code: 'JE',
  },
  {
    country_name_en: 'Jordan',
    country_name_es: 'Jordania',
    country_code: 'JO',
  },
  {
    country_name_en: 'Kazakhstan',
    country_name_es: 'Kazajistán',
    country_code: 'KZ',
  },
  {
    country_name_en: 'Kenya',
    country_name_es: 'Kenia',
    country_code: 'KE',
  },
  {
    country_name_en: 'Korea - Republic of (South)',
    country_name_es: 'Corea del Sur',
    country_code: 'KR',
  },
  {
    country_name_en: 'Kuwait',
    country_name_es: 'Kuwait',
    country_code: 'KW',
  },
  {
    country_name_en: 'Kyrgyzstan',
    country_name_es: 'Kirguistán',
    country_code: 'KG',
  },
  {
    country_name_en: 'Laos',
    country_name_es: 'Laos',
    country_code: 'LA',
  },
  {
    country_name_en: 'Latvia',
    country_name_es: 'Letonia',
    country_code: 'LV',
  },
  {
    country_name_en: 'Lebanon',
    country_name_es: 'Líbano',
    country_code: 'LB',
  },
  {
    country_name_en: 'Lesotho',
    country_name_es: 'Lesoto',
    country_code: 'LS',
  },
  {
    country_name_en: 'Libya',
    country_name_es: 'Libia',
    country_code: 'LY',
  },
  {
    country_name_en: 'Liechtenstein',
    country_name_es: 'Liechtenstein',
    country_code: 'LI',
  },
  {
    country_name_en: 'Lithuania',
    country_name_es: 'Lituania',
    country_code: 'LT',
  },
  {
    country_name_en: 'Luxembourg',
    country_name_es: 'Luxemburgo',
    country_code: 'LU',
  },
  {
    country_name_en: 'Macau (CN)',
    country_name_es: 'Macao (China)',
    country_code: 'MO',
  },
  {
    country_name_en: 'Macedonia',
    country_name_es: 'Macedonia del Norte',
    country_code: 'MK',
  },
  {
    country_name_en: 'Madagascar',
    country_name_es: 'Madagascar',
    country_code: 'MG',
  },
  {
    country_name_en: 'Malawi',
    country_name_es: 'Malaui',
    country_code: 'MW',
  },
  {
    country_name_en: 'Malaysia',
    country_name_es: 'Malasia',
    country_code: 'MY',
  },
  {
    country_name_en: 'Maldives',
    country_name_es: 'Maldivas',
    country_code: 'MV',
  },
  {
    country_name_en: 'Mali',
    country_name_es: 'Malí',
    country_code: 'ML',
  },
  {
    country_name_en: 'Malta',
    country_name_es: 'Malta',
    country_code: 'MT',
  },
  {
    country_name_en: 'Marshall Islands',
    country_name_es: 'Islas Marshall',
    country_code: 'MH',
  },
  {
    country_name_en: 'Martinique (FR)',
    country_name_es: 'Martinica (Francia)',
    country_code: 'MQ',
  },
  {
    country_name_en: 'Mauritania',
    country_name_es: 'Mauritania',
    country_code: 'MR',
  },
  {
    country_name_en: 'Mauritius',
    country_name_es: 'Mauricio',
    country_code: 'MU',
  },
  {
    country_name_en: 'Mayotte (FR)',
    country_name_es: 'Mayotte (Francia)',
    country_code: 'YT',
  },
  {
    country_name_en: 'Mexico',
    country_name_es: 'México',
    country_code: 'MX',
  },
  {
    country_name_en: 'Micronesia, Federated States of',
    country_name_es: 'Micronesia',
    country_code: 'FM',
  },
  {
    country_name_en: 'Moldova Republic of',
    country_name_es: 'Moldavia',
    country_code: 'MD',
  },
  {
    country_name_en: 'Monaco',
    country_name_es: 'Mónaco',
    country_code: 'MC',
  },
  {
    country_name_en: 'Mongolia',
    country_name_es: 'Mongolia',
    country_code: 'MN',
  },
  {
    country_name_en: 'Montenegro',
    country_name_es: 'Montenegro',
    country_code: 'ME',
  },
  {
    country_name_en: 'Montserrat (UK)',
    country_name_es: 'Montserrat (Reino Unido)',
    country_code: 'MS',
  },
  {
    country_name_en: 'Morocco',
    country_name_es: 'Marruecos',
    country_code: 'MA',
  },
  {
    country_name_en: 'Mozambique',
    country_name_es: 'Mozambique',
    country_code: 'MZ',
  },
  {
    country_name_en: 'Myanmar',
    country_name_es: 'Myanmar (Birmania)',
    country_code: 'MM',
  },
  {
    country_name_en: 'Namibia',
    country_name_es: 'Namibia',
    country_code: 'NA',
  },
  {
    country_name_en: 'Nepal',
    country_name_es: 'Nepal',
    country_code: 'NP',
  },
  {
    country_name_en: 'Netherlands',
    country_name_es: 'Países Bajos',
    country_code: 'NL',
  },
  {
    country_name_en: 'Netherlands Antilles (NL)',
    country_name_es: 'Antillas Neerlandesas',
    country_code: 'AN',
  },
  {
    country_name_en: 'New Caledonia (FR)',
    country_name_es: 'Nueva Caledonia (Francia)',
    country_code: 'NC',
  },
  {
    country_name_en: 'New Zealand',
    country_name_es: 'Nueva Zelanda',
    country_code: 'NZ',
  },
  {
    country_name_en: 'Nicaragua',
    country_name_es: 'Nicaragua',
    country_code: 'NI',
  },
  {
    country_name_en: 'Niger',
    country_name_es: 'Níger',
    country_code: 'NE',
  },
  {
    country_name_en: 'Nigeria',
    country_name_es: 'Nigeria',
    country_code: 'NG',
  },
  {
    country_name_en: 'Niue',
    country_name_es: 'Niue',
    country_code: 'NU',
  },
  {
    country_name_en: 'Norfolk Island (AU)',
    country_name_es: 'Isla Norfolk (Australia)',
    country_code: 'NF',
  },
  {
    country_name_en: 'Northern Mariana Islands (US)',
    country_name_es: 'Islas Marianas del Norte (EE. UU.)',
    country_code: 'MP',
  },
  {
    country_name_en: 'Norway',
    country_name_es: 'Noruega',
    country_code: 'NO',
  },
  {
    country_name_en: 'Oman',
    country_name_es: 'Omán',
    country_code: 'OM',
  },
  {
    country_name_en: 'Pakistan',
    country_name_es: 'Pakistán',
    country_code: 'PK',
  },
  {
    country_name_en: 'Palestine',
    country_name_es: 'Palestina',
    country_code: 'PS',
  },
  {
    country_name_en: 'Panama',
    country_name_es: 'Panamá',
    country_code: 'PA',
  },
  {
    country_name_en: 'Papua New Guinea',
    country_name_es: 'Papúa Nueva Guinea',
    country_code: 'PG',
  },
  {
    country_name_en: 'Paraguay',
    country_name_es: 'Paraguay',
    country_code: 'PY',
  },
  {
    country_name_en: 'Peru',
    country_name_es: 'Perú',
    country_code: 'PE',
  },
  {
    country_name_en: 'Philippines',
    country_name_es: 'Filipinas',
    country_code: 'PH',
  },
  {
    country_name_en: 'Pitcairn Islands (UK)',
    country_name_es: 'Islas Pitcairn (Reino Unido)',
    country_code: 'PN',
  },
  {
    country_name_en: 'Poland',
    country_name_es: 'Polonia',
    country_code: 'PL',
  },
  {
    country_name_en: 'Portugal',
    country_name_es: 'Portugal',
    country_code: 'PT',
  },
  {
    country_name_en: 'Puerto Rico (US)',
    country_name_es: 'Puerto Rico (EE. UU.)',
    country_code: 'PR',
  },
  {
    country_name_en: 'Qatar',
    country_name_es: 'Catar',
    country_code: 'QA',
  },
  {
    country_name_en: 'Reunion (FR)',
    country_name_es: 'Reunión (Francia)',
    country_code: 'RE',
  },
  {
    country_name_en: 'Romania',
    country_name_es: 'Rumania',
    country_code: 'RO',
  },
  {
    country_name_en: 'Russia',
    country_name_es: 'Rusia',
    country_code: 'RU',
  },
  {
    country_name_en: 'Rwanda',
    country_name_es: 'Ruanda',
    country_code: 'RW',
  },
  {
    country_name_en: 'Saint Helena (UK)',
    country_name_es: 'Santa Elena (Reino Unido)',
    country_code: 'SH',
  },
  {
    country_name_en: 'Saint Kitts and Nevis',
    country_name_es: 'San Cristóbal y Nieves',
    country_code: 'KN',
  },
  {
    country_name_en: 'Saint Lucia',
    country_name_es: 'Santa Lucía',
    country_code: 'LC',
  },
  {
    country_name_en: 'Saint Vincent and the Grenadines',
    country_name_es: 'San Vicente y las Granadinas',
    country_code: 'VC',
  },
  {
    country_name_en: 'Saint-Barthélemy',
    country_name_es: 'San Bartolomé',
    country_code: 'BL',
  },
  {
    country_name_en: 'Saint-Martin (FR)',
    country_name_es: 'San Martín (Francia)',
    country_code: 'MF',
  },
  {
    country_name_en: 'San Marino',
    country_name_es: 'San Marino',
    country_code: 'SM',
  },
  {
    country_name_en: 'Saudi Arabia',
    country_name_es: 'Arabia Saudita',
    country_code: 'SA',
  },
  {
    country_name_en: 'Senegal',
    country_name_es: 'Senegal',
    country_code: 'SN',
  },
  {
    country_name_en: 'Serbia',
    country_name_es: 'Serbia',
    country_code: 'RS',
  },
  {
    country_name_en: 'Seychelles',
    country_name_es: 'Seychelles',
    country_code: 'SC',
  },
  {
    country_name_en: 'Sierra Leone',
    country_name_es: 'Sierra Leona',
    country_code: 'SL',
  },
  {
    country_name_en: 'Singapore',
    country_name_es: 'Singapur',
    country_code: 'SG',
  },
  {
    country_name_en: 'Slovakia',
    country_name_es: 'Eslovaquia',
    country_code: 'SK',
  },
  {
    country_name_en: 'Slovenia',
    country_name_es: 'Eslovenia',
    country_code: 'SI',
  },
  {
    country_name_en: 'Solomon Islands',
    country_name_es: 'Islas Salomón',
    country_code: 'SB',
  },
  {
    country_name_en: 'Somalia',
    country_name_es: 'Somalia',
    country_code: 'SO',
  },
  {
    country_name_en: 'South Africa',
    country_name_es: 'Sudáfrica',
    country_code: 'ZA',
  },
  {
    country_name_en: 'South Georgia & South Sandwich Islands (UK)',
    country_name_es: 'Islas Georgias del Sur y Sandwich del Sur (Reino Unido)',
    country_code: 'GS',
  },
  {
    country_name_en: 'South Sudan',
    country_name_es: 'Sudán del Sur',
    country_code: 'SS',
  },
  {
    country_name_en: 'Spain',
    country_name_es: 'España',
    country_code: 'ES',
  },
  {
    country_name_en: 'Sri Lanka',
    country_name_es: 'Sri Lanka',
    country_code: 'LK',
  },
  {
    country_name_en: 'Suriname',
    country_name_es: 'Surinam',
    country_code: 'SR',
  },
  {
    country_name_en: 'Svalbard and Jan Mayen Islands',
    country_name_es: 'Svalbard y Jan Mayen',
    country_code: 'SJ',
  },
  {
    country_name_en: 'Swaziland',
    country_name_es: 'Esuatini',
    country_code: 'SZ',
  },
  {
    country_name_en: 'Sweden',
    country_name_es: 'Suecia',
    country_code: 'SE',
  },
  {
    country_name_en: 'Switzerland',
    country_name_es: 'Suiza',
    country_code: 'CH',
  },
  {
    country_name_en: 'Taiwan',
    country_name_es: 'Taiwán',
    country_code: 'TW',
  },
  {
    country_name_en: 'Tajikistan',
    country_name_es: 'Tayikistán',
    country_code: 'TJ',
  },
  {
    country_name_en: 'Tanzania',
    country_name_es: 'Tanzania',
    country_code: 'TZ',
  },
  {
    country_name_en: 'Thailand',
    country_name_es: 'Tailandia',
    country_code: 'TH',
  },
  {
    country_name_en: 'Timor-Leste',
    country_name_es: 'Timor Oriental',
    country_code: 'TL',
  },
  {
    country_name_en: 'Togo',
    country_name_es: 'Togo',
    country_code: 'TG',
  },
  {
    country_name_en: 'Tokelau',
    country_name_es: 'Tokelau',
    country_code: 'TK',
  },
  {
    country_name_en: 'Tonga',
    country_name_es: 'Tonga',
    country_code: 'TO',
  },
  {
    country_name_en: 'Trinidad and Tobago',
    country_name_es: 'Trinidad y Tobago',
    country_code: 'TT',
  },
  {
    country_name_en: 'Tunisia',
    country_name_es: 'Túnez',
    country_code: 'TN',
  },
  {
    country_name_en: 'Turkey',
    country_name_es: 'Turquía',
    country_code: 'TR',
  },
  {
    country_name_en: 'Turkmenistan',
    country_name_es: 'Turkmenistán',
    country_code: 'TM',
  },
  {
    country_name_en: 'Turks and Caicos Islands (UK)',
    country_name_es: 'Islas Turcas y Caicos (Reino Unido)',
    country_code: 'TC',
  },
  {
    country_name_en: 'Tuvalu',
    country_name_es: 'Tuvalu',
    country_code: 'TV',
  },
  {
    country_name_en: 'Uganda',
    country_name_es: 'Uganda',
    country_code: 'UG',
  },
  {
    country_name_en: 'Ukraine',
    country_name_es: 'Ucrania',
    country_code: 'UA',
  },
  {
    country_name_en: 'United Arab Emirates',
    country_name_es: 'Emiratos Árabes Unidos',
    country_code: 'AE',
  },
  {
    country_name_en: 'United Kingdom',
    country_name_es: 'Reino Unido',
    country_code: 'GB',
  },
  {
    country_name_en: 'United States',
    country_name_es: 'Estados Unidos',
    country_code: 'US',
  },
  {
    country_name_en: 'Uruguay',
    country_name_es: 'Uruguay',
    country_code: 'UY',
  },
  {
    country_name_en: 'Uzbekistan',
    country_name_es: 'Uzbekistán',
    country_code: 'UZ',
  },
  {
    country_name_en: 'Vanuatu',
    country_name_es: 'Vanuatu',
    country_code: 'VU',
  },
  {
    country_name_en: 'Venezuela',
    country_name_es: 'Venezuela',
    country_code: 'VE',
  },
  {
    country_name_en: 'Vietnam',
    country_name_es: 'Vietnam',
    country_code: 'VN',
  },
  {
    country_name_en: 'Virgin Islands (US)',
    country_name_es: 'Islas Vírgenes (EE. UU.)',
    country_code: 'VI',
  },
  {
    country_name_en: 'Wallis and Futuna (FR)',
    country_name_es: 'Wallis y Futuna (Francia)',
    country_code: 'WF',
  },
  {
    country_name_en: 'Western Sahara',
    country_name_es: 'Sahara Occidental',
    country_code: 'EH',
  },
  {
    country_name_en: 'Yemen',
    country_name_es: 'Yemen',
    country_code: 'YE',
  },
  {
    country_name_en: 'Zambia',
    country_name_es: 'Zambia',
    country_code: 'ZM',
  },
  {
    country_name_en: 'Zimbabwe',
    country_name_es: 'Zimbabue',
    country_code: 'ZW',
  },
]

export const LICENSES = [
  {
    license_letter: 'R',
    license_name_en: 'Rookie',
    license_name_es: 'Novato',
    license_color: 'red',
  },
  {
    license_letter: 'D',
    license_name_en: 'Class D',
    license_name_es: 'Clase D',
    license_color: 'orange',
  },
  {
    license_letter: 'C',
    license_name_en: 'Class C',
    license_name_es: 'Clase C',
    license_color: 'yellow',
  },
  {
    license_letter: 'B',
    license_name_en: 'Class B',
    license_name_es: 'Clase B',
    license_color: 'green',
  },
  {
    license_letter: 'A',
    license_name_en: 'Class A',
    license_name_es: 'Clase A',
    license_color: 'blue',
  },
  {
    license_letter: 'P',
    license_name_en: 'Pro / WC',
    license_name_es: 'Pro / CM',
    license_color: 'gray',
  },
]

export const CATEGORIES = [
  {
    category_name_en: 'Sports Cars',
    category_name_es: 'Deportivos',
    category_code: 'sports-cars',
    category_table_name: 'driver-stats-sports_car',
  },
  {
    category_name_en: 'Formula Cars',
    category_name_es: 'Monoplazas',
    category_code: 'formula-cars',
    category_table_name: 'driver-stats-formula_car',
  },
  {
    category_name_en: 'Oval',
    category_name_es: 'Óvalos',
    category_code: 'oval',
    category_table_name: 'driver-stats-oval',
  },
  {
    category_name_en: 'Dirt Oval',
    category_name_es: 'Óvalos de Tierra',
    category_code: 'dirt-oval',
    category_table_name: 'driver-stats-dirt_oval',
  },
  {
    category_name_en: 'Dirt Road',
    category_name_es: 'Circuitos de Tierra',
    category_code: 'dirt-road',
    category_table_name: 'driver-stats-dirt_road',
  },
]
